### ISSUE TITLE
Why the number of shapelets I get is different with the reported results in your paper??

### ISSUE THREAD

**Issue by real2fish** [House1993/ELIS#1]
Hi,
    I have run your code on the same datasets by your script, but why I get different shapelet number with your result?
    For example, shapelets number of _Beef_ is {10, 8, 3, 13 ,9} in your paper, but {7, 8, 13, 9, 9} in my results.

**Comment by House1993** [comment]
> ```
> Hi,
> I have run your code on the same datasets by your script, but why I get different shapelet number with your result?
> For example, shapelets number of _Beef_ is {10, 8, 3, 13 ,9} in your paper, but {7, 8, 13, 9, 9} in my results.
> ```

I have checked my result file and get the same shapelets number as my paper. The difference between us may be caused by the environment. Specifically, my OS is Ubuntu and my C++ version is 7.3.0(It is my current C++ version, not the version that I did experiments before. But I can redo the experiments successfully). By the way, I am willing to share my experiment logs and results to you if you need them :)

**Comment by real2fish** [comment]
> > ```
> > Hi,
> > I have run your code on the same datasets by your script, but why I get different shapelet number with your result?
> > For example, shapelets number of _Beef_ is {10, 8, 3, 13 ,9} in your paper, but {7, 8, 13, 9, 9} in my results.
> > ```
> 
> I have checked my result file and get the same shapelets number as my paper. The difference between us may be caused by the environment. Specifically, my OS is Ubuntu and my C++ version is 7.3.0(It is my current C++ version, not the version that I did experiments before. But I can redo the experiments successfully). By the way, I am willing to share my experiment logs and results to you if you need them :)

Sorry for the late reply. I have just reproduced the experiment on a Ubuntu environment and get the same results as your paper. That's quite amazing. Thanks for your help!
